// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WiredBrainCoffee.EmployeeManager.Data;

#nullable disable

namespace WiredBrainCoffee.EmployeeManager.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20220924152614_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 5,
                            FirstName = "Hy",
                            IsDeveloper = true,
                            LastName = "Ho Nhat"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FirstName = "A",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            FirstName = "B",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            FirstName = "C",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            FirstName = "D",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 4,
                            FirstName = "E",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            FirstName = "F",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            FirstName = "G",
                            IsDeveloper = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            FirstName = "H",
                            IsDeveloper = true,
                            LastName = "Nguyen"
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Data.Models.Employee", b =>
                {
                    b.HasOne("WiredBrainCoffee.EmployeeManager.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
